import React from 'react';
import { ShieldCheck, Lock, AlertCircle, FileText } from 'lucide-react';

export const LegalDisclaimerPage: React.FC = () => {
  return (
    <div className="max-w-4xl mx-auto p-6 sm:p-8 space-y-6 text-zinc-100">
      <div className="flex items-center gap-3 border-b border-zinc-800 pb-4">
        <div className="w-10 h-10 rounded-2xl bg-emerald-500/10 text-emerald-400 flex items-center justify-center border border-emerald-500/20">
          <FileText className="w-5 h-5" />
        </div>
        <div>
          <h1 className="text-xl font-bold">PowerChain AI Protocol Disclaimer & Terms</h1>
          <p className="text-xs text-zinc-400">Legal, ESG Compliance & DePIN Network Regulatory Framework</p>
        </div>
      </div>

      <div className="p-4 bg-amber-500/10 border border-amber-500/20 rounded-2xl flex items-start gap-3">
        <AlertCircle className="w-5 h-5 text-amber-400 shrink-0 mt-0.5" />
        <div className="space-y-1 text-xs text-amber-200">
          <p className="font-bold">Important On-Chain Energy Credit Notice</p>
          <p>
            PowerChain (PWRC) tokens and Renewable Energy Certificates (RECs) represent verified kilowatt-hour (kWh) and megawatt-hour (MWh) power grid telemetry verified by Pyth Network price oracles and decentralized node telemetry.
          </p>
        </div>
      </div>

      <div className="space-y-4 text-xs text-zinc-300 leading-relaxed">
        <section className="space-y-2 p-4 bg-zinc-900/60 rounded-2xl border border-zinc-800">
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <ShieldCheck className="w-4 h-4 text-emerald-400" /> 1. Telemetry & Oracle Verification
          </h2>
          <p>
            Grid output measurements, battery state-of-charge (BESS), and carbon reduction metrics are continuously polled from physical edge hardware nodes and submitted to the Pyth Solana oracle network. PowerChain does not guarantee zero latency during unexpected utility regional grid curtailments.
          </p>
        </section>

        <section className="space-y-2 p-4 bg-zinc-900/60 rounded-2xl border border-zinc-800">
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <Lock className="w-4 h-4 text-emerald-400" /> 2. Multi-Party Computation (MPC) & Treasury Security
          </h2>
          <p>
            Treasury transactions, credit clearing, and fee routing require threshold key shard authorizations (2-of-3 MPC shards). User private keys are protected under sovereign cryptographic vault standards.
          </p>
        </section>

        <section className="space-y-2 p-4 bg-zinc-900/60 rounded-2xl border border-zinc-800">
          <h2 className="text-sm font-bold text-white flex items-center gap-2">
            <FileText className="w-4 h-4 text-emerald-400" /> 3. ESG & Scope 1-3 Carbon Offsets
          </h2>
          <p>
            All carbon accounting generated by PowerChain AI is structured in compliance with the GHG Protocol corporate standard. Corporate users remain responsible for validating localized regional regulatory filings.
          </p>
        </section>
      </div>
    </div>
  );
};
