import React, { useState } from 'react';
import { Mail, RefreshCw, Send, FileEdit, CheckCircle, AlertCircle, ShieldAlert, Sparkles } from 'lucide-react';
import { fetchEnergyEmails, createGmailDraft, sendGmailMessage, googleSignIn, getAccessToken, GmailMessageSummary } from '../services/gmail';
import { summarizeEmailThreadWithLLM } from '../utils/email-parser';
import { auditLogger } from '../utils/audit-logger';
import { ChatMessage } from '../types';

interface GmailChatWidgetProps {
  onInsertPrompt: (promptText: string) => void;
  onAddMessage?: (message: ChatMessage) => void;
  gridPerformanceSummary?: string;
  agentId?: string;
}

export const GmailChatWidget: React.FC<GmailChatWidgetProps> = ({
  onInsertPrompt,
  onAddMessage,
  gridPerformanceSummary = 'Total Output: 420.5 MWh | Avg Latency: 14.8 ms | Node Uptime: 99.98% | Efficiency: 98.4%',
  agentId = 'analyst',
}) => {
  const [emails, setEmails] = useState<GmailMessageSummary[]>([]);
  const [loading, setLoading] = useState(false);
  const [summarizingId, setSummarizingId] = useState<string | null>(null);
  const [status, setStatus] = useState<string | null>(null);

  // Draft/Send Confirmation Modal State
  const [confirmModal, setConfirmModal] = useState<{
    isOpen: boolean;
    type: 'draft' | 'send';
    to: string;
    subject: string;
    body: string;
  }>({
    isOpen: false,
    type: 'draft',
    to: '',
    subject: '',
    body: '',
  });

  const handleFetchEmails = async () => {
    setLoading(true);
    setStatus('Fetching energy grid emails via OAuth2...');
    try {
      let token = await getAccessToken();
      if (!token) {
        const authRes = await googleSignIn();
        token = authRes?.accessToken || null;
      }
      if (!token) {
        setStatus('Please connect Google Workspace in Settings.');
        setLoading(false);
        return;
      }

      const list = await fetchEnergyEmails();
      setEmails(list);
      if (list.length === 0) {
        setStatus('No recent energy grid emails found in Gmail.');
      } else {
        setStatus(`Successfully loaded ${list.length} energy emails.`);
      }
    } catch (err: any) {
      setStatus(`Gmail Error: ${err.message || err}`);
    } finally {
      setLoading(false);
    }
  };

  const handleSummarizeThread = async (email: GmailMessageSummary) => {
    setSummarizingId(email.id);
    setStatus(`Summarizing email thread: "${email.subject}" via PowerAI LLM...`);
    try {
      const chatMsg = await summarizeEmailThreadWithLLM(email, agentId);
      if (onAddMessage) {
        onAddMessage(chatMsg);
        setStatus(`Summary added to chat stream for "${email.subject}".`);
      } else {
        onInsertPrompt(chatMsg.text);
      }
    } catch (err: any) {
      setStatus(`Summarization error: ${err.message || err}`);
    } finally {
      setSummarizingId(null);
    }
  };

  const handleOpenDraftModal = (email?: GmailMessageSummary) => {
    const recipient = email ? email.from : 'grid-counterparty@powerchain.network';
    const subject = email ? `Re: ${email.subject}` : 'PowerChain Energy Grid Settlement & Performance Summary';
    const body = `Hello,\n\nHere is our automated grid telemetry and performance digest generated by PowerChain AI:\n\n- ${gridPerformanceSummary}\n- Settlement Status: Cleared on Solana Mainnet via PWRC credits\n- System Status: Nominal\n\nPlease let us know if you require additional meter verification logs.\n\nBest regards,\nPowerChain AI Grid Operator`;

    setConfirmModal({
      isOpen: true,
      type: 'draft',
      to: recipient,
      subject,
      body,
    });
  };

  const handleOpenSendModal = (email?: GmailMessageSummary) => {
    const recipient = email ? email.from : 'grid-counterparty@powerchain.network';
    const subject = email ? `Re: ${email.subject}` : 'PowerChain Energy Grid Settlement Digest';
    const body = `Hello,\n\nRegarding energy node telemetry:\n\n${gridPerformanceSummary}\n\nAll protocol fees have been routed to the fee wallet PWRC111111111111111111111111111111111111111.\n\nBest regards,\nPowerChain AI`;

    setConfirmModal({
      isOpen: true,
      type: 'send',
      to: recipient,
      subject,
      body,
    });
  };

  const handleExecuteConfirmedAction = async () => {
    setLoading(true);
    const { type, to, subject, body } = confirmModal;
    setConfirmModal((prev) => ({ ...prev, isOpen: false }));

    try {
      if (type === 'draft') {
        setStatus('Creating draft in Gmail...');
        const draftRes = await createGmailDraft(to, subject, body);
        setStatus(`Gmail Draft Created! (Draft ID: ${draftRes.id || 'ok'})`);
        auditLogger.log({
          action: 'Create Gmail Draft',
          category: 'transaction',
          details: `Created draft to ${to} with subject "${subject}"`,
          status: 'success',
        });
      } else {
        setStatus('Sending email via Gmail API...');
        const sendRes = await sendGmailMessage(to, subject, body);
        setStatus(`Email Sent Successfully! (Message ID: ${sendRes.id || 'ok'})`);
        auditLogger.log({
          action: 'Send Gmail Message',
          category: 'transaction',
          details: `Sent email to ${to} with subject "${subject}"`,
          status: 'success',
        });
      }
    } catch (err: any) {
      setStatus(`Failed to execute Gmail operation: ${err.message || err}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="p-3 bg-gray-50 dark:bg-zinc-900/90 border border-gray-200 dark:border-zinc-800 rounded-xl space-y-3">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <div className="w-6 h-6 rounded-lg bg-red-500/10 border border-red-500/20 flex items-center justify-center text-red-500">
            <Mail className="w-3.5 h-3.5" />
          </div>
          <div>
            <h4 className="text-xs font-bold text-gray-900 dark:text-zinc-100">Gmail Grid Integration</h4>
            <p className="text-[9.5px] text-gray-400">Summarize energy threads & draft replies directly</p>
          </div>
        </div>

        <button
          onClick={handleFetchEmails}
          disabled={loading}
          className="px-2.5 py-1 rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold text-[10px] flex items-center gap-1 transition-colors cursor-pointer"
        >
          <RefreshCw className={`w-3 h-3 ${loading ? 'animate-spin' : ''}`} />
          Fetch Emails
        </button>
      </div>

      {status && (
        <p className="text-[10px] font-mono text-emerald-600 dark:text-emerald-400 bg-emerald-500/10 px-2.5 py-1 rounded-lg">
          {status}
        </p>
      )}

      {/* Quick Email Action Buttons */}
      <div className="flex flex-wrap gap-2">
        <button
          onClick={() => handleOpenDraftModal()}
          className="px-2.5 py-1 rounded-lg bg-white dark:bg-zinc-950 border border-gray-200 dark:border-zinc-800 hover:border-emerald-500 text-[10px] font-semibold text-gray-800 dark:text-zinc-200 flex items-center gap-1 transition-colors cursor-pointer"
        >
          <FileEdit className="w-3 h-3 text-emerald-500" />
          Draft Energy Performance Email
        </button>
        <button
          onClick={() => handleOpenSendModal()}
          className="px-2.5 py-1 rounded-lg bg-white dark:bg-zinc-950 border border-gray-200 dark:border-zinc-800 hover:border-emerald-500 text-[10px] font-semibold text-gray-800 dark:text-zinc-200 flex items-center gap-1 transition-colors cursor-pointer"
        >
          <Send className="w-3 h-3 text-sky-500" />
          Send Settlement Report
        </button>
      </div>

      {/* Email Thread List */}
      {emails.length > 0 && (
        <div className="space-y-1.5 pt-2 border-t border-gray-200 dark:border-zinc-800">
          <p className="text-[10px] font-bold text-gray-400 uppercase tracking-wider">Loaded Threads</p>
          <div className="space-y-1.5 max-h-40 overflow-y-auto custom-scrollbar">
            {emails.map((email) => (
              <div
                key={email.id}
                className="p-2 bg-white dark:bg-zinc-950 rounded-lg border border-gray-100 dark:border-zinc-800 flex items-center justify-between gap-2"
              >
                <div className="min-w-0 flex-1">
                  <p className="text-[11px] font-bold text-gray-900 dark:text-zinc-100 truncate">{email.subject}</p>
                  <p className="text-[9.5px] text-gray-400 truncate">{email.snippet}</p>
                </div>
                <div className="flex items-center gap-1 shrink-0">
                  <button
                    onClick={() => handleSummarizeThread(email)}
                    disabled={summarizingId === email.id}
                    className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 hover:bg-emerald-500/20 text-[9.5px] font-bold transition-colors cursor-pointer flex items-center gap-1"
                    title="Summarize in AI Chat via LLM"
                  >
                    <Sparkles className={`w-2.5 h-2.5 ${summarizingId === email.id ? 'animate-spin' : ''}`} />
                    {summarizingId === email.id ? 'Summarizing...' : 'Summarize email'}
                  </button>
                  <button
                    onClick={() => handleOpenDraftModal(email)}
                    className="px-2 py-0.5 rounded bg-zinc-800 text-zinc-200 hover:bg-zinc-700 text-[9.5px] font-semibold transition-colors cursor-pointer"
                    title="Draft Reply"
                  >
                    Reply
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* USER CONFIRMATION DIALOG MODAL (MANDATORY per Workspace Skill guidelines) */}
      {confirmModal.isOpen && (
        <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-xs flex items-center justify-center p-4">
          <div className="bg-white dark:bg-zinc-900 border border-gray-200 dark:border-zinc-800 rounded-2xl w-full max-w-md p-5 shadow-2xl space-y-4">
            <div className="flex items-center gap-3 text-emerald-600 dark:text-emerald-400">
              <ShieldAlert className="w-6 h-6" />
              <h3 className="font-bold text-base text-gray-900 dark:text-zinc-100">
                Confirm Gmail Operation
              </h3>
            </div>

            <p className="text-xs text-gray-600 dark:text-zinc-300">
              {confirmModal.type === 'draft'
                ? 'Create a new draft email in your Google Workspace Gmail account?'
                : 'Send an email directly from your Google Workspace Gmail account?'}
            </p>

            <div className="p-3 bg-gray-50 dark:bg-zinc-950 rounded-xl border border-gray-200 dark:border-zinc-800 space-y-2 text-xs">
              <div>
                <span className="text-gray-400 text-[10px]">Recipient:</span>
                <p className="font-mono font-bold text-gray-900 dark:text-zinc-100">{confirmModal.to}</p>
              </div>
              <div>
                <span className="text-gray-400 text-[10px]">Subject:</span>
                <p className="font-semibold text-gray-900 dark:text-zinc-100">{confirmModal.subject}</p>
              </div>
              <div>
                <span className="text-gray-400 text-[10px]">Body Preview:</span>
                <p className="font-mono text-[10px] text-gray-600 dark:text-zinc-400 whitespace-pre-wrap line-clamp-4">
                  {confirmModal.body}
                </p>
              </div>
            </div>

            <div className="flex items-center justify-end gap-2 pt-2">
              <button
                onClick={() => setConfirmModal((prev) => ({ ...prev, isOpen: false }))}
                className="px-4 py-2 rounded-xl bg-gray-200 dark:bg-zinc-800 text-gray-800 dark:text-zinc-200 text-xs font-bold hover:bg-gray-300 dark:hover:bg-zinc-700 transition-colors cursor-pointer"
              >
                Cancel
              </button>
              <button
                onClick={handleExecuteConfirmedAction}
                className="px-4 py-2 rounded-xl bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold shadow-md transition-colors cursor-pointer"
              >
                Confirm & Execute
              </button>
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
